name: Scheduled FitBot run

on:
  workflow_dispatch:
  schedule:
  - cron: "50 16 * * 1,6"
  - cron: "50 7 * * 3"
jobs:
  wait_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Wait until 09:00:00 UTC
        run: |
          # Lista de horas objetivo
          target_times=("17:00:00" "08:00:00")
          echo "🎯 Target times: ${target_times[*]}"

          executed=0

          while [ $executed -eq 0 ]; do
            current_time=$(date -u +"%H:%M")
            echo "⏱️ Current UTC time: $current_time"

            for target in "${target_times[@]}"; do
              if [ "$current_time" = "$target" ]; then
                echo "✅ Target time $target matched! Executing action..."
                executed=1
                break
              fi
            done

            sleep 5  # Refresca cada 5 segundos
          done
      - name: Do the real work
        run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals={'\"1\":{\"time\":\"1900\"\,\"name\":\"CrossFit\"}\,\"3\":{\"time\":\"1900\"\,\"name\":\"CrossFit\"}\,\"5\":{\"time\":\"1000\"\,\"name\":\"CrossFit\"}'} -e box-name=crossfitdrkacoruna -e box-id=9942 -e days-in-advance=3 jotero185/fitbot
